### ISSUE TITLE
Immediate Roadmap

### ISSUE THREAD

**Issue by apockill** [UrbanMachine/node_helpers#3]
This repo is freshly migrated from Urban Machine's private monorepo. I've combed through it and documented what I can, I've also upgraded it from Humble to Jazzy and fixed minor issues where I found them. Tests also pass!

Things to look out for:
- Issues relating to the Humble -> Jazzy upgrade
- Incorrect documentation
- probably more?

Next up:
- [ ] Add an actual, working showcase project
- [x] Add CI
- [ ] Publish the companion package, `urdf_helpers`
- [ ] Add node_helpers to the `create-ros-app` default dependencies
